# coding: utf-8

"""
    Yagna Payment API

     Invoicing and Payments is a fundamental area of Yagna Ecosystem functionality. It includes aspects of communication between Requestor, Provider and a selected Payment Platform, which becomes crucial when Activities are executed in the context of negotiated Agreements. Yagna applications must be able to exercise various payment models, and the Invoicing/Payment-related communication is happening in parallel to Activity control communication. To define functional patterns of Requestor/Provider interaction in this area, Payment API is specified.  An important principle of the Yagna Payment API is that the actual payment transactions are hidden behind the Invoice flow. In other words, a Yagna Application on Requestor side isn’t expected to trigger actual payment transactions. Instead it is expected to receive and accept Invoices raised by the Provider - based on Application’s Invoice Accept notifications, the Payment API implementation orchestrates the payment via a configured Payment platform.  **NOTE: This specification is work-in-progress.**   # noqa: E501

    The version of the OpenAPI document: 1.2.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import payment
from payment.api.requestor_state_api import RequestorStateApi  # noqa: E501
from src.rest import ApiException


class TestRequestorStateApi(unittest.TestCase):
    """RequestorStateApi unit test stubs"""

    def setUp(self):
        self.api = payment.api.requestor_state_api.RequestorStateApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_activity_state(self):
        """Test case for get_activity_state

        Get state of specified Activity.  # noqa: E501
        """
        pass

    def test_get_activity_usage(self):
        """Test case for get_activity_usage

        Get usage of specified Activity.  # noqa: E501
        """
        pass

    def test_get_running_command(self):
        """Test case for get_running_command

        Get running command for a specified Activity.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
